# Configuration for pull request and issue labeler

# Pull Request labels
"documentation":
  - docs/**/*
  - "*.md"
  - CONTRIBUTING.md
  - README.md
  - CHANGELOG.md

"enhancement":
  - src/**/*

"bug":
  - src/**/*

"tests":
  - src/test/**/*
  - "**/*.test.ts"

"dependencies":
  - package.json
  - package-lock.json

"github-actions":
  - .github/workflows/*
